---
- name: Setup Environment
  hosts: localhost
  remote_user: root

  tasks:
    - name: Test we can connect as root for setup
      ansible.builtin.ping:
      become: yes
      become_user: root

    - name: setup sudoless access
      lineinfile:
        path: /etc/sudoers
        line: "pinkman    ALL=(ALL) NOPASSWD:ALL"
      become: yes
      become_user: root
    
    - name: setup global git config
      command:
        cmd: "{{ item }}"
      with_items:
        - git config --global user.email "tonyschndr@gmail.com"
        - git config --global user.name "Tony Schneider"     

    - name: setup vimrc
      copy:
        dest: ~/.vimrc
        content: |
          au! BufNewFile,BufReadPost *.{yaml,yml} set filetype=yaml foldmethod=indent
          autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab


    - name: Install virtualization packages
      apt:
        state: present
        name:
          - qemu-kvm
          - qemu
          - libvirt-clients
          - libvirt-daemon-system
          - bridge-utils
          - vagrant
          - ebtables
          - dnsmasq-base
          - libxslt-dev
          - libxml2-dev
          - libvirt-dev
          - zlib1g-dev
          - ruby-dev
          - libguestfs-tools
          - ruby-libvirt
      become: yes
      become_user: root
      when: ansible_os_family == 'Debian' 

    - name: install yum-utils
      yum:
        name: yum-utils
        state: latest
      become: yes
      become_user: root
